### PR TITLE
Add Save Game Free

### PR DESCRIPTION
**Pull request by EmpireWorld**
A Free and Complete Save Game Solution.

[Save Game Free](https://www.assetstore.unity3d.com/#!/content/81519)

### CODE REVIEW

**Comment by RyanNielson** [comment]
Thanks for the suggestion. The list should be in alphabetical order so could you please move this above Unistorm. Also, could you add a more detailed or improved description. What you have now is kind of redundant as it basically just repeats the name of the asset.

Maybe mention one or two of the most useful features in the asset.

**Comment by EmpireWorld** [comment]
I have reordered it.

The Save Game Free 2.0 is going to released on Unity Asset Store so i will add web and encryption features.

Can you wait for that or merge it now and make a new pull request for that?

Thanks.

**Comment by RyanNielson** [comment]
I can wait if you'd like, that's no problem.

**Comment by EmpireWorld** [comment]
@RyanNielson The Save Game Free Gold Update is now available on [GitHub](https://github.com/BayatGames/SaveGameFree) and [itch.io](https://bayat.itch.io/save-game-free) and in asset store still in review. But you can merge the pull request.

Thanks.

**Pull request closed without merging**
