### PR TITLE
Added Fast Platform Switch

### PR DESCRIPTION
**Pull request by JiMMaR**
Switching between platforms on Unity is pretty slow, when developing for example on iOS and Android, switching between targets takes longer and longer as the project's assets grow.
Fast Platform Switch caches the modified assets state to make switching between targets pretty fast.
It's a must have if you are targeting more than one platform

### CODE REVIEW

**Comment by Mazyod** [comment]
+!

**Comment by RyanNielson** [comment]
This package doesn't seem to have been updated in quite a while. Is it still supported in Unity 5?

**Comment by JiMMaR** [comment]
@RyanNielson I've been using it on Unity 5 with no issues, but I just tried to contact the developer to confirm, I'll post back when/if I get a reply

**Comment by RyanNielson** [comment]
Thanks for looking into it. Looking forward to hearing back from you. It seems like an incredibly useful asset.

**Comment by JiMMaR** [comment]
@RyanNielson It's been a week and I got no reply from the developer, not sure if the tool is still being developed or not [even though it does support Unity 5 as far as I know].
Feel free to merge or reject this PR.

**Pull request closed without merging**
