### PR TITLE
Added Crystal AI

### PR DESCRIPTION
**Pull request by ThelDoctor**

### CODE REVIEW

**Comment by RyanNielson** [comment]
Can you please read the `CONTRIBUTING.md` file in the base of the repo and modify your PR. Specifically the section about PR titles and descriptions. It's be great to hear why you think this project is great and better than any of the alternatives out there.

Thanks

**Comment by ThelDoctor** [comment]
Well, to my knowledge, there isn't any other utility AI available in C# that is compatible with unity and that is also open source. Is there anything in particular in the description I've added that you have an objection to?
P.S. I did read the CONTRIBUTING.md, maybe I missed something?

**Comment by RyanNielson** [comment]
Well the description you added to the readme is fine. I'm just moreso looking for a more detailed description in the PR description section itself, that's what I'm referring to. 

Maybe a quick overview of features or unique aspects of your project. Stuff like that. Haven't had time to check out your link yet, which is why I like to just get a quick overview in the PR description. Though you look to have a Github page that I might be able to get all the info I need from.

**Comment by ThelDoctor** [comment]
Oh, I see! Here's a short description of Crystal:
`Crystal AI is an artificial intelligence framework based on state-of-the-art research in utility theory and decision making. Crystal enables developers express their ideas about how the AI should behave naturally thus reducing the complexity involved in creating believable AI behaviours.

Features
* Fast
* Zero Dependencies
* Can Debug AI Outside the Unity Editor
* Expandable
* Low Memory Usage
* Intuitive Design
* Comprehensive Test Suite 3000+ Unit Tests
* Written in C#
* AI Execution Scheduler for complete control over the AI execution cycle and ms used.
* Execution Time Limiter
* Easily Extensible
* Open Source
`

**Pull request merged**
